### ISSUE TITLE
Problem handeling objects in usersession!

### ISSUE THREAD

**Issue by newmedia** [lonnieezell/codeigniter-forensics#9] opened 2012-02-26 22:52 UTC
Forensics gives an error on line 440 of Profiler.php when a value is an object.. The following code fixes this:

if (is_object($val)) {
        $output[$key] = json_encode($val);
} else {
        $output[$key] = htmlspecialchars(stripslashes($val));
}

**Comment by mckaygerhard** [comment] 2018-03-08 14:19
yeah its problem of the conversion to chars..  i have some patches to solve it, but i ust talk with @lonnieezell to send pull request..

**Comment by lonnieezell** [comment] 2018-03-08 14:36
@mckaygerhard No need to ask me anything about it - just submit a PR and we'll go from there.

**Comment by mckaygerhard** [comment] 2018-03-08 14:49
ah you are alive here! its just that you are working so many in CI4 that any other thing for olders CI3 and CI2 inclusivelly are "too away"..  

ok i'll send soe this week.. there are many fixeds..

**Comment by mckaygerhard** [comment] 2018-03-30 19:08
i made many changes to my fork in codeignitepower but i cannot reproduce this issue.. maybe if a better explanation of .. i test with some json coding rules but if not i propose close it then

**Comment by mckaygerhard** [comment] 2018-04-01 15:43
not confirmed and made a pull request in #31 please @lonnieezell merged and close this issue

now moved to solve others issues here..

**Closed** 2018-04-02 03:10 UTC
